import { useState } from 'react';
import type { ReviewCardProps } from '@/shared/types';
import { Button } from '@/renderer/components/ui/button';
import { Copy, Twitter, Check } from 'lucide-react';

/**
 * Share card - Final card with sharing options
 */
export const ShareCard: React.FC<ReviewCardProps> = ({ data }) => {
  const { shareStats, badges } = data;
  const [copied, setCopied] = useState(false);

  const earnedBadges = badges.filter(b => b.earned);

  const handleCopyStats = () => {
    const text = `🎄 My 2025 Claude Code Year in Review generated by OpenOwl 🎄

✨ ${shareStats.totalTokensFormatted} tokens generated
💰 $${shareStats.totalCost.toFixed(0)} spent on AI
🏆 ${shareStats.totalSessions} coding sessions
🔥 ${shareStats.longestStreak}-day hot streak
🎖️ ${earnedBadges.length} badges earned

Check out OpenOwl: https://github.com/antonbelev/open-owl

#OpenOwl #ClaudeCode #YearInReview #AI #Coding`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleTweet = async () => {
    const text = encodeURIComponent(
      `🎄 My 2025 Claude Code Year in Review generated by OpenOwl 🎄

✨ ${shareStats.totalTokensFormatted} tokens generated
💰 $${shareStats.totalCost.toFixed(0)} spent on AI
🏆 ${shareStats.totalSessions} coding sessions
🔥 ${shareStats.longestStreak}-day hot streak

Check out yours at https://github.com/antonbelev/open-owl

#OpenOwl #ClaudeCode #YearInReview #AI #Coding`
    );

    const url = `https://twitter.com/intent/tweet?text=${text}`;

    // Use Electron's openExternal to open in default browser
    if (window.electronAPI?.openExternal) {
      await window.electronAPI.openExternal(url);
    } else {
      // Fallback for non-Electron environments
      window.open(url, '_blank');
    }
  };

  return (
    <div className="text-center text-white">
      <p className="text-white/70 text-lg mb-4">Share Your 2025 Journey!</p>

      {/* Preview card */}
      <div className="bg-gradient-to-br from-slate-800 to-slate-900 rounded-xl p-6 max-w-sm mx-auto border border-white/10 shadow-xl mb-6">
        <div className="text-center">
          <div className="text-2xl mb-2">🎄 ❄️ 🎅</div>
          <h3 className="text-lg font-bold text-amber-400 mb-4">
            My 2025 Claude Code Year in Review
          </h3>

          <div className="grid grid-cols-2 gap-3 mb-4">
            <div className="bg-white/5 rounded p-2">
              <div className="text-xl font-bold text-amber-400">
                {shareStats.totalTokensFormatted}
              </div>
              <div className="text-xs text-white/60">tokens</div>
            </div>
            <div className="bg-white/5 rounded p-2">
              <div className="text-xl font-bold text-emerald-400">
                ${shareStats.totalCost.toFixed(0)}
              </div>
              <div className="text-xs text-white/60">spent</div>
            </div>
            <div className="bg-white/5 rounded p-2">
              <div className="text-xl font-bold">{shareStats.totalSessions}</div>
              <div className="text-xs text-white/60">sessions</div>
            </div>
            <div className="bg-white/5 rounded p-2">
              <div className="text-xl font-bold text-orange-400">🔥 {shareStats.longestStreak}</div>
              <div className="text-xs text-white/60">day streak</div>
            </div>
          </div>

          <div className="text-xs text-white/40">
            <span className="text-lg mr-1">🦉</span>
            OpenOwl • github.com/antonbelev/open-owl
          </div>
        </div>
      </div>

      {/* Share buttons */}
      <div className="flex justify-center gap-3">
        <Button
          onClick={handleCopyStats}
          variant="outline"
          className="bg-white/10 border-white/20 text-white hover:bg-white/20"
        >
          {copied ? (
            <>
              <Check className="w-4 h-4 mr-2" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="w-4 h-4 mr-2" />
              Copy Stats
            </>
          )}
        </Button>

        <Button onClick={handleTweet} className="bg-sky-500 hover:bg-sky-600 text-white">
          <Twitter className="w-4 h-4 mr-2" />
          Tweet It!
        </Button>
      </div>

      <p className="mt-6 text-white/50 text-sm">
        Thanks for being part of the OpenOwl community! 🦉
      </p>
    </div>
  );
};
